# Generated by Django 4.0.4 on 2022-06-05 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_playeritem_rename_stat_itemstat_playeritemstat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='access_token',
        ),
        migrations.DeleteModel(
            name='PlayerItemStat',
        ),
    ]
